# Generated by Django 4.1.3 on 2022-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artwork_title", models.CharField(max_length=200)),
                ("year_completed", models.IntegerField(default=2022)),
            ],
        ),
    ]
