# Generated by Django 4.1.3 on 2022-12-06 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artwork",
            old_name="artwork_title",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="year_completed",
        ),
        migrations.AddField(
            model_name="artwork",
            name="demo_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="source_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
