# Generated by Django 4.1.3 on 2022-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0003_tag_artwork_created_artwork_vote_ratio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[
                    {"one", 1},
                    {2, "two"},
                    {"three", 3},
                    {4, "four"},
                    {5, "five"},
                ],
                max_length=200,
            ),
        ),
    ]
