# Generated by Django 4.1.3 on 2022-12-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0005_alter_review_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[
                    (1, "poor"),
                    (2, "fair"),
                    (3, "good"),
                    (4, "excellent"),
                    (5, "sublime"),
                ],
                max_length=200,
            ),
        ),
    ]
