# Generated by Django 4.1.3 on 2022-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0007_alter_review_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="default_image.jpg", null=True, upload_to=""
            ),
        ),
    ]
