# Generated by Django 4.1.3 on 2023-01-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0009_artwork_critic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="value",
        ),
        migrations.AddField(
            model_name="review",
            name="What_might_work",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="What_needs_work",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="What_works",
            field=models.TextField(blank=True, null=True),
        ),
    ]
