# Generated by Django 4.1.3 on 2023-01-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0010_remove_review_value_review_what_might_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[
                    ("one_star", 1),
                    ("two_stars", 2),
                    ("three_stars", 3),
                    ("four_stars", 4),
                    ("five_stars", 5),
                ],
                default="None",
                max_length=200,
            ),
        ),
    ]
