# Generated by Django 4.1.3 on 2023-01-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0011_review_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="body",
        ),
    ]
