# Generated by Django 4.1.3 on 2023-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0012_remove_review_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="value",
            new_name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="Sum_it_up",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
