# Generated by Django 4.1.3 on 2023-01-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0005_profile_username"),
        ("artworks", "0013_rename_value_review_rating_review_sum_it_up"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="critic",
        ),
        migrations.AddField(
            model_name="artwork",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="panelists.profile",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="year_created",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
