# Generated by Django 4.1.3 on 2023-01-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0014_remove_artwork_critic_artwork_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(max_length=2000),
        ),
    ]
