# Generated by Django 4.1.3 on 2023-01-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0017_artwork_my_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="my_goals",
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
