# Generated by Django 4.1.3 on 2023-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0018_alter_artwork_my_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="my_goals",
            field=models.TextField(
                blank=True, default="Topic for discussion", null=True
            ),
        ),
    ]
