# Generated by Django 4.1.3 on 2023-01-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0019_alter_artwork_my_goals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="my_goals",
        ),
        migrations.AddField(
            model_name="artwork",
            name="topic",
            field=models.TextField(
                blank=True, default="My goals for the work", null=True
            ),
        ),
    ]
