# Generated by Django 4.1.3 on 2023-01-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0021_alter_artwork_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="topic",
            field=models.TextField(
                blank=True, default="Write your goals for the work here", null=True
            ),
        ),
    ]
