# Generated by Django 4.1.3 on 2023-01-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0009_delete_criteria"),
        ("artworks", "0023_alter_artwork_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="panelists.profile",
            ),
        ),
    ]
