# Generated by Django 4.1.3 on 2023-01-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0009_delete_criteria"),
        ("artworks", "0024_review_owner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("owner",), ("artwork",)},
        ),
    ]
