# Generated by Django 4.1.3 on 2023-01-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0025_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
