# Generated by Django 4.1.3 on 2023-02-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0009_delete_criteria"),
        ("artworks", "0026_alter_artwork_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="What_might_work",
            new_name="comments",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="year_created",
        ),
        migrations.RemoveField(
            model_name="review",
            name="Sum_it_up",
        ),
        migrations.RemoveField(
            model_name="review",
            name="What_needs_work",
        ),
        migrations.RemoveField(
            model_name="review",
            name="What_works",
        ),
        migrations.AlterField(
            model_name="artwork",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="panelists.profile",
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="topic",
            field=models.TextField(
                blank=True, default="I would like feedback on:", null=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(
                choices=[("up", "Up Vote"), ("down", "Down Vote")], max_length=200
            ),
        ),
    ]
