# Generated by Django 4.1.3 on 2023-02-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0027_rename_what_might_work_review_comments_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="rating",
            new_name="value",
        ),
    ]
