# Generated by Django 4.1.3 on 2023-02-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0028_rename_rating_review_value"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
