# Generated by Django 4.1.3 on 2023-02-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0030_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={"ordering": ["owner", "-vote_ratio", "-vote_total", "title"]},
        ),
    ]
