# Generated by Django 4.1.3 on 2023-02-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0031_alter_artwork_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="star_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
