# Generated by Django 4.1.3 on 2023-02-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0032_artwork_star_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="star_count",
        ),
    ]
