# Generated by Django 4.1.3 on 2022-12-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="social_website",
            new_name="website",
        ),
        migrations.AlterField(
            model_name="profile",
            name="brief_bio",
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
