# Generated by Django 4.1.3 on 2023-01-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0003_profile_media_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="social_insta",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_other",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_twitter",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
