# Generated by Django 4.1.3 on 2023-01-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0005_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="brief_bio",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
