# Generated by Django 4.1.3 on 2023-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0007_remove_profile_profle_image_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
