# Generated by Django 4.1.3 on 2023-01-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0008_profile_pronouns"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Criteria",
        ),
    ]
