# Generated by Django 4.1.3 on 2023-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0009_delete_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
