# Generated by Django 4.1.3 on 2023-02-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0011_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("true", "Moderator"), ("false", "Artist")],
                max_length=200,
                null=True,
            ),
        ),
    ]
